export interface Order{
    DIST?:string;
    DESC?: string;
    HEAT?: string;
    ITEM: string;
    ITEMREFC?: string;
    L7008?: Boolean;
    L7009?: Boolean;
    L7014?: Boolean;
    LBFT?: Number;
    LDFAR?:  Boolean;
    LENGTH?: Number;
    LFAR?: Boolean;
    LOC?: string;
    LOCKED?: Boolean;
    LTAA?: Boolean;
    MAXL?: Number;
    MELT?: string;
    MFG?: string;
    MILL_NO?: string;
    MINL?: Number;
    PCS?: Number;
    POLINE: Number;
    PONO: Number;
    REC_DATE?: Date;
    REMOTE?: Number;
    STATUS?: Number;
    TAG?: string;
    TAG_COMMENT?: string;
    TAGCON?: string;
    TAG_QTY?: Number;
    UOM?: string;
    VENDOR?: string;
    WIDTH?: Number;
}